common: &common
  username: myfx
  adapter: postgresql
  host: localhost
#
development:
  <<: *common
  database: myfx_development
  host: localhost
#
production:
  <<: *common
  database: myfx_production
#
test:
  <<: *common
  database: myfx_test
  host: localhost
