require 'rubygems' # not necessary with ruby 1.9 but included for completeness
require 'twilio-ruby'

# put your own credentials here
account_sid = 'ACe258aaabe53da86578b9d53591760950'
auth_token = '35455067054ffa37809ce7a5f43e541b'

# set up a client to talk to the Twilio REST API
@client = Twilio::REST::Client.new account_sid, auth_token